name: Build Windows x64

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:

jobs:
  build-windows-x64:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Initialize
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Setup MSYS2 MINGW64
        uses: msys2/setup-msys2@e9898307ac31d1a803454791be09ab9973336e1c
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-zeromq
            mingw-w64-x86_64-libsodium
            mingw-w64-x86_64-hidapi
            mingw-w64-x86_64-unbound
            mingw-w64-x86_64-protobuf
            mingw-w64-x86_64-libusb
            mingw-w64-x86_64-libevent
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            mingw-w64-x86_64-ntldd
            git
            base-devel
            wget
            unzip

      - name: Install boost v1.87.0
        run: |
          wget https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-boost-1.87.0-1-any.pkg.tar.zst
          pacman -U --noconfirm mingw-w64-x86_64-boost-1.87.0-1-any.pkg.tar.zst

      - name: Build Monero project
        run: |
          cd submodules/monero-cpp/external/monero-project

          mkdir -p build/release
          cd build/release

          cmake -G "MSYS Makefiles" \
            -D STATIC=ON \
            -D ARCH="x86-64" \
            -D BUILD_64=ON \
            -D CMAKE_BUILD_TYPE=Release \
            -D BUILD_TAG="win-x64" \
            -D CMAKE_TOOLCHAIN_FILE="../../cmake/64-bit-toolchain.cmake" \
            -D MSYS2_FOLDER=$(cd $MINGW_PREFIX/.. && pwd -W) \
            ../../

          make wallet cryptonote_protocol -j$(nproc)

      - name: Build Monero C++
        run: |
          cmake -S submodules/monero-cpp -B submodules/monero-cpp/build -DCMAKE_POLICY_DEFAULT_CMP0167=NEW
          cmake --build submodules/monero-cpp/build

      - name: Upload monero-cpp libraries
        uses: actions/upload-artifact@v7
        with:
          name: libmonero-cpp-win-x64
          path: |
            submodules/monero-cpp/build/libmonero-cpp.dll
            submodules/monero-cpp/build/libmonero-cpp.dll.a

      - name: Build monero-c
        run: |
          cmake -S MoneroC -B MoneroC/build -DCMAKE_POLICY_DEFAULT_CMP0167=NEW
          cmake --build MoneroC/build

      - name: Upload monero-c libraries
        uses: actions/upload-artifact@v7
        with:
          name: libmonero-c-win-x64
          path: |
            MoneroC/build/libmonero-c.dll
            MoneroC/build/libmonero-c.dll.a

      - name: Download daemon
        run: |
          set -ex
          MONERO_VERSION=0.18.5.1
          FILE="monero-win-x64-v${MONERO_VERSION}.zip"
          FILE_CHECKSUM="cf2ae8273977697d9ef2031c7337b781e6e5936578f602444b2990a173a2437d"

          cd /tmp
          wget -qO "${FILE}" "https://downloads.getmonero.org/cli/${FILE}"
          echo "${FILE_CHECKSUM} ${FILE}" | sha256sum -c -
          
          mkdir -p bin
          unzip -j "${FILE}" "*/monerod.exe" -d bin

          mkdir -p "${GITHUB_WORKSPACE}/monero-cli"
          cp bin/monerod.exe "${GITHUB_WORKSPACE}/monero-cli/"

      - name: Node start
        shell: pwsh
        run: |
          Start-Process -FilePath "monero-cli\monerod.exe" -ArgumentList @(
            "--p2p-bind-ip=0.0.0.0",
            "--p2p-bind-port=18080",
            "--rpc-bind-port=18081",
            "--log-level=2",
            "--rpc-bind-ip=0.0.0.0",
            "--confirm-external-bind",
            "--regtest",
            "--no-igd",
            "--hide-my-port",
            "--non-interactive"
          )

      - name: Build CsharpTestApp
        shell: pwsh
        run: dotnet build CsharpTestApp -maxcpucount:1 -c Release

      - name: Copy native C++ library
        run: cp submodules/monero-cpp/build/libmonero-cpp.dll CsharpTestApp/bin/Release/net10.0/

      - name: Copy native C library
        run: cp MoneroC/build/libmonero-c.dll CsharpTestApp/bin/Release/net10.0/monero-c.dll

      - name: Run CsharpTestApp
        shell: pwsh
        run: |
          cd CsharpTestApp/bin/Release/net10.0
          ./CsharpTestApp.exe
